#!/bin/sh
set -e

PREREQ=""
prereqs() {
	echo "$PREREQ"
}

case "$1" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /bin/date /bin
copy_exec /bin/grep /bin
copy_exec /sbin/dumpe2fs /sbin
